name: Build Executable

on:
  workflow_dispatch:  # This allows manual triggers only

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Ensure you have PyInstaller installed

    - name: Build executable
      run: |
        pyinstaller --onefile \
                     --name "Unity Game Installer" \  # Replace with your app name
                     --version-file version.txt \  # Optional: specify version file
                     --icon app.ico \  # Replace with your icon path
                     main.py  # Replace with your main script name

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Updated to use v3
      with:
        name: executable
        path: dist/your_script.exe  # Adjust to match the name of your executable
