name: Build Executable

on:
  workflow_dispatch:  # This allows manual triggers only

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Ensure you have PyInstaller installed

    - name: Create version file
      run: |
        echo "VSVersionInfo(" > version.txt
        echo "  ffi=FixedFileInfo(" >> version.txt
        echo "    filevers=(0,2,1,0)," >> version.txt
        echo "    prodvers=(0,2,1,0)," >> version.txt
        echo "    mask=0x3f," >> version.txt
        echo "    flags=0x0," >> version.txt
        echo "    OS=0x40004," >> version.txt
        echo "    fileType=0x1," >> version.txt
        echo "    subtype=0x0," >> version.txt
        echo "    date=(0,0)" >> version.txt
        echo "  )," >> version.txt
        echo "  kids=[StringFileInfo([StringTable('040904E4', [" >> version.txt
        echo "    StringStruct('CompanyName', 'Top T Tech')," >> version.txt
        echo "    StringStruct('FileDescription', 'Unity Game Launcher')," >> version.txt
        echo "    StringStruct('FileVersion', '0.2.1')," >> version.txt
        echo "    StringStruct('InternalName', 'UnityGameLauncher')," >> version.txt
        echo "    StringStruct('OriginalFilename', 'UnityGameLauncher.exe')," >> version.txt
        echo "    StringStruct('ProductName', 'Unity Game Launcher')," >> version.txt
        echo "    StringStruct('ProductVersion', '0.2.1')," >> version.txt
        echo "  ])])," >> version.txt
        echo "  VarFileInfo([VarStruct('Translation', [1033, 1252])])" >> version.txt
        echo ")" >> version.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --name "Unity Game Launcher" --version-file version.txt --icon app.ico main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3  # Updated to use v3
      with:
        name: executable
        path: dist/Unity_Game_Launcher.exe  # Adjust to match the name of your executable
