name: Build Executable

on:
  workflow_dispatch:  # Allows manual triggers only

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Ensure PyInstaller is installed

    - name: Build executable
      run: |
        pyinstaller --onefile --name "Unity Game Launcher" --version-file version_info.txt --icon app.ico main.py  # Updated command

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Unity-Game-Launcher
        path: dist/Unity_Game_Launcher.exe  # Adjust to the correct path
